version: "3.8"

services:
  db:
    image: postgres:16
    container_name: gin_postgres
    restart: always
    environment:
      POSTGRES_USER: wmsuser
      POSTGRES_PASSWORD: wmspassword
      POSTGRES_DB: wmsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wmsuser"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: wms-app
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: wmsuser
      DB_PASSWORD: wmspassword
      DB_NAME: wmsdb
      DB_PORT: 5432
    ports:
      - "8080:8080"

volumes:
  postgres_data:
