name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.3'
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install dependencies
        run: go mod download
        working-directory: wms-app
      - name: Build
        run: go build -v -o wms-app ./cmd
        working-directory: wms-app
      - name: Run tests
        run: go test ./...
        working-directory: wms-app
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: wms-app-binary
          path: wms-app/cmd/wms-app
